# Sample .travis.yml for R projects
language: r
# warnings_are_errors: false

matrix:
  include:
    - os: linux
      dist: trusty
      r: bioc-devel
      script:
        - Rscript -e 'covr::codecov(type="anystuff")'
    - os: osx
      r: bioc-release
  allow_failures:
    - os: osx

bioc_check: true

env:
 global:
   - CRAN: http://cran.rstudio.com

r_github_packages: tidyverse/ggplot2

notifications:
  email:
    on_success: change
    on_failure: change
  