# Sample .travis.yml for R projects
language: r
# warnings_are_errors: false

matrix:
  include:
    - stage: covr
      script: 
        - Rscript -e 'covr::codecov(type="all")'
        - R CMD INSTALL .
        - Rscript -e 'pkgdown::build_site()'
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: false
          local-dir: docs
          on:
            branch: feature/pkgdown
  allow_failures:
    - os: osx

bioc_check: true

env:
 global:
   - CRAN: http://cran.rstudio.com

r_github_packages: tidyverse/ggplot2

notifications:
  email:
    on_success: change
    on_failure: change
  